### PR TITLE
Retry UEFI boot Configuration

### PR DESCRIPTION
**Pull request by derekhiggins**
This consistently fails on some HW, retry until we
find a proper solution.

### CODE REVIEW

**Comment by dtantsur** [comment]
/lgtm

Should not harm, but I wonder if we need to do it upstream as well (e.g. by retrying the specific mount operation).

**Comment by dtantsur** [comment]
@derekhiggins please do propose this change to metal3 upstream as well

**Comment by derekhiggins** [comment]
> @derekhiggins please do propose this change to metal3 upstream as well

will do

**Comment by derekhiggins** [comment]
> @derekhiggins please do propose this change to metal3 upstream as well

Upstream PR here https://github.com/metal3-io/ironic-agent-image/pull/19

**Pull request merged**
