### PR TITLE
OCPBUGS-20486: fix eventlet regression with Python 3.6

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by sdodson** [comment]
This failure seems pretty consistent, likely need to reach out to ART.
```
Error: Failed to download metadata for repo 'localdev-rhel-8-server-ironic-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
localdev-rhel-8-server-ose-rpms                 0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'localdev-rhel-8-server-ose-rpms':
  - Curl error (6): Couldn't resolve host name for https://ocp-artifacts.hosts.prod.psi.rdu2.redhat.com/pub/RHOCP/plashets/4.11/stream/el8/latest/x86_64/os/repodata/repomd.xml [Could not resolve host: ocp-artifacts.hosts.prod.psi.rdu2.redhat.com]
Error: Failed to download metadata for repo 'localdev-rhel-8-server-ose-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: localdev-openstack-16-for-rhel-8-rpms, localdev-rhel-8-appstream-rpms, localdev-rhel-8-baseos-rpms, localdev-rhel-8-codeready-builder-rpms, localdev-rhel-8-fast-datapath-rpms, localdev-rhel-8-rt-rpms, localdev-rhel-8-server-ansible-2.9-rpms, localdev-rhel-8-server-ironic-rpms, localdev-rhel-8-server-ose-rpms
```

**Comment by dtantsur** [comment]
@sdodson that's an artefact of our container building, this is the actual failure:
```
Error: Unable to find a match: python3-eventlet >= 0.30.2-3.el8
```
The reason for that is that it takes around 6 hours for a package to get to production repositories. All we need is to wait a bit more. I'll probably recheck the first thing tomorrow.

**Comment by dtantsur** [comment]
Something went wrong with tagging, we're retrying it (will need to wait again).

**Pull request merged**
