### PR TITLE
NO-ISSUE: Bump ironic projects versions

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by dtantsur** [comment]
/lgtm

But you need a jira reference or NO-ISSUE @elfosardo

**Comment by elfosardo** [comment]
> /lgtm
> 
> But you need a jira reference or NO-ISSUE @elfosardo

yep, I was undecided if actually bulding an actual BUG for this, but NO-ISSUE is fine

**Comment by elfosardo** [comment]
/retest
looks like the provisioning completed, trying one more time

**Comment by elfosardo** [comment]
/retest
fix has merged

**Comment by elfosardo** [comment]
/retest
failure not related to this patch

**Comment by elfosardo** [comment]
/retest
issue with repo mirror service

**Pull request merged**
