### PR TITLE
Rework the install_coreos deploy step per approved design

### PR DESCRIPTION
**Pull request by dtantsur**
Changes for https://github.com/metal3-io/metal3-docs/pull/180:
* Pass parameters through configdrive and standard instance_info
* Add error handling

### CODE REVIEW

**Comment by dtantsur** [comment]
/hold

Testing

**Comment by dtantsur** [comment]
/hold cancel

Seems to work \o/

**Review by elfosardo — APPROVED** [review]

**Review by iurygregory — APPROVED** [review]

**Comment by dtantsur** [comment]
/override ci/prow/e2e-metal-ipi
/override ci/prow/e2e-metal-ipi-virtualmedia

This project is not even in the CI...

**Pull request merged**
