### PR TITLE
Rename packages list

### PR DESCRIPTION
**Pull request by elfosardo**
Use .ocp extension to be explicit on the purpose.

### CODE REVIEW

**Comment by dtantsur** [comment]
Please don't remove Dockerfile, I'm using it for quay.io publishing (and we'll probably use it for okd version later on).

**Comment by elfosardo** [comment]
@dtantsur sure!

**Comment by dtantsur** [comment]
/lgtm cancel

Hmm, if you rename the packages file, the upstream Dockerfile will no longer work. I guess removing the upstream Dockerfile was the right thing to do, just could you please also remove the paragraph about quay.io images from README and update the `docker build` command there?

**Comment by elfosardo** [comment]
> /lgtm cancel
> 
> Hmm, if you rename the packages file, the upstream Dockerfile will no longer work. I guess removing the upstream Dockerfile was the right thing to do, just could you please also remove the paragraph about quay.io images from README and update the `docker build` command there?

@dtantsur will do! :)

**Pull request merged**
