### PR TITLE
METAL-925: Install ironic-python-agent from source

### PR DESCRIPTION
**Pull request by elfosardo**
Also adds script to check requirement release match

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
this should fail, it's missing proper system config, but  we still can verify dependencies are correctly installed

**Comment by elfosardo** [comment]
/retest
so many no route to host

**Comment by dtantsur** [comment]
Looks good so far.

**Comment by elfosardo** [comment]
> Looks good so far.

yeah, I'm just not sure if we're missing some config, the CI failures scare me :)
going to retest once more before digging into logs

**Comment by elfosardo** [comment]
/retest
no route to host issue

**Comment by elfosardo** [comment]
the errors in the failures are not related to this change
overriding failed CI jobs

**Comment by elfosardo** [comment]
/override ci/prow/e2e-metal-ipi-ovn-ipv6 ci/prow/e2e-metal-ipi-virtualmedia

**Pull request merged**
