### PR TITLE
OWNERS: add Iury, remove Julia and Russell

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Review by juliakreger — COMMENTED** [review]
Yes please!

**Review by juliakreger — COMMENTED** [review]
/lgtm

**Comment by elfosardo** [comment]
this https://github.com/openshift/release/pull/18932 should fix the issue with the CI

**Comment by ashcrow** [comment]
Given this is an access change in the `OWNERS` file I'm overriding the requirement for needing a bugzilla.

**Pull request merged**
